### ISSUE TITLE
Minor oversight with Disguises' schematics

### ISSUE THREAD

**Issue by Iridar** [WOTCStrategyOverhaul/InfiltratorsDisguises#4]
If you purchase ADVENT Disguise schematic before the Civilian Disguise schematic, you will be unable to purchase the Civilian Disguise schematic. 

The issue appears only without Prototype Armory module.

Probably the same issue would occur if you were to purchase Holographic Disguise schematic before purchasing ADVENT and Civilian schematics.

**Comment by cannonfodder1** [comment]
The specific case where the Holographic Disguise hides the previous two tiers should be kept, as it is superior to both of the previous disguises. The Civilian and Advent disguises are sidegrades however, and neither should be hidden when the other is purchased.
